name: Deploy Test GCP

on:
    push:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: 34.125.175.246
                  username: berylmalikaveta
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /home/berylmalikaveta/challange-platinum
                      git fetch --all
                      git merge --no-commit --no-ff origin/master  # Merge changes without committing
                      git status  # Check for conflicts
                      if [ -n "$(git status --porcelain)" ]; then  # Check if there are conflicts
                        git merge --abort  # Abort merge if conflicts exist
                        echo "Conflicts detected, please resolve them manually"
                      else
                        git commit -m "Merge changes from origin/master"
                        git pull origin master
                        pm2 restart all
                      fi
