name: Pull Changes from Master Branch

on:
    push:
        branches:
            - master

jobs:
    pull_changes:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Pull changes on the server
              uses: appleboy/ssh-action@master
              with:
                  host: 34.125.175.246
                  username: beylmalikaveta
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: 22
                  script: |
                      cd /home/berylmalikaveta/challange-platinum
                      git pull origin master
                      pm2 restart all
